### PR TITLE
added keep_args cli argument

### PR DESCRIPTION
**Pull request by jspaezp**
discussed on https://github.com/wfondrie/mokapot/issues/31

I was also able to note the definition of the fixtures for files in the tests, would you believe moving to `pytest-datadir` would be helpful (https://pypi.org/project/pytest-datadir/)? In my experience it makes a breeze to deal with files for testing.

lmk if you want me to change anything else.

### CODE REVIEW

**Comment by wfondrie** [comment]
The checks aren't failing currently because of your PR --- It seems I left a test docstring poorly formatted (and incomplete 😱 ) that fails with the updated version of black. I'm going to fix it quickly, then you can sync your branch and the rest of the tests should run!

**Comment by wfondrie** [comment]
I've just merged an update to the tests into master. Please sync your fork with master and then the tests should run here. Thanks!

**Comment by wfondrie** [comment]
> I was also able to note the definition of the fixtures for files in the tests, would you believe moving to pytest-datadir would be helpful (https://pypi.org/project/pytest-datadir/)? In my experience it makes a breeze to deal with files for testing.

I just looked into and it seems like it would be useful. I'll open it as an issue. Thanks!

**Comment by jspaezp** [comment]
@wfondrie I think i pulled the changes to my branch. lmk if that is enough (I have always found tricky to merge upstream branches to my pull requests ... sigh ...)

**Comment by wfondrie** [comment]
This looks good to me. I'll merge it now. There's a couple things other things I want to add, but expect a new release later today.

Thanks for being our fist contributor! 🎉

**Pull request merged**
