### PR TITLE
Small changes for FlashLFQ writer

### PR DESCRIPTION
**Pull request by unholyparrot**
I am using mokapot (v0.10.0) as an embedded rescoring engine within the ms2rescore package (https://github.com/compomics/ms2rescore, v3.0.3), which you may have heard of for rescoring results from sage (https://github.com/lazear/sage, v0.14.6).

I've tried doing label-free quantification with FlashLFQ GUI (v1.2.6), as you kindly provided the writer for its "Generic" format, and bumped into zero intensity for all quantified proteins. Checking the `results.sage.ms2rescore.mokapot.flashlfq` and `*.raw` files with FreeStyle, I found the unnecessary subdivision of the retention time for conversion to FlashLFQ compatible format, as the retention time is supposed to be minutes, but it's already in minutes.

To test the theory, I manually deleted the division in the source files of ms2rescore venv in `lib/python3.10/site-packages/mokapot/writers/flashlfq.py` at line 115 and resubmitted the job to ms2rescore and later to FlashLFQ.

As a result, all proteins are now appropriately quantified.

Please consider this PR if you find it useful.

### CODE REVIEW

**Comment by jspaezp** [comment]
Humm I am not 100% sure if it is a valid assumption that the RT from sage will always be in seconds. Would you mind leaving the details on how the mzml was generated?

**Comment by unholyparrot** [comment]
According to sage documentation, retention time is given in minutes. 

mzml was generated with ThermoRawFileParser1.4.3 in command line mode with default parameters.

**Comment by jspaezp** [comment]
Cool!

for future reference: https://github.com/lazear/sage/blob/73eaf49a4e53179b9bd5329bc1f085835f5f3987/crates/sage-cloudpath/src/mzml.rs#L250-L258

Sage does seem to check the unit at parse time of the mzml to make the units minutes. So I guess that if we specify in the mokapot docs that the rt column is meant to be in minutes, we could go ahead and do that. (not sure if other tools that write .pin files will default to minutes ...)

https://github.com/lazear/sage/blob/73eaf49a4e53179b9bd5329bc1f085835f5f3987/crates/sage-cloudpath/src/tdf.rs#L35 + https://github.com/MannLabs/timsrust/issues/34 also makes sure that .d files are in seconds in sage.

@wfondrie do you recall why that `/60` is there? is there any tool that writes the .pin in seconds (I think we should be able to remove it safely ...)?

**Review by wfondrie — APPROVED** [review]
I think this should be good. We're in the midst of some other large updates, so I'm going to go ahead and merge it.

**Pull request merged**
